### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by GarimaPawar**
Review my code Grroot members

### CODE REVIEW

**Comment by sambit985** [comment]
@GarimaPawar  Explain what you have used for this instapage..

**Comment by GarimaPawar** [comment]
> @GarimaPawar Explain what you have used for this instapage..

I have used only html and css language .... Css apply internally inside the head section and content in body part... I had linked API for access material icons from that website....

**Comment by sambit985** [comment]
> > @GarimaPawar Explain what you have used for this instapage..
> 
> I have used only html and css language .... Css apply internally inside the head section and content in body part... I had linked API for access material icons from that website....

I know mam already told how to link api and where to copy that link...By the way your page looking stylish.

**Comment by GarimaPawar** [comment]
> > > @GarimaPawar Explain what you have used for this instapage..
> > 
> > 
> > @sambit985  have used only html and css language .... Css apply internally inside the head section and content in body part... I had linked API for access material icons from that website....
> 
> I know mam already told how to link api and where to copy that link...By the way your page looking stylish.

**Pull request merged**
